# Generated by Django 2.2.6 on 2019-10-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
