# Generated by Django 2.2.6 on 2019-10-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('part_of_speech', models.CharField(max_length=20)),
                ('meaning', models.CharField(max_length=40)),
                ('example_sentence', models.TextField()),
                ('sentence_interpretation', models.TextField()),
                ('word_of_frequency', models.IntegerField(default=0)),
            ],
        ),
    ]
