# Generated by Django 2.2.6 on 2019-10-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_text', '0002_userinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinput',
            name='times',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userinput',
            name='word_except',
            field=models.BooleanField(default=False),
        ),
    ]
