# Generated by Django 2.2.6 on 2019-10-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_text', '0004_auto_20191019_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframe',
            name='example_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataframe',
            name='sentence_interpretation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
