# Generated by Django 2.2.3 on 2019-10-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_text', '0006_mouigosa_suneung'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mouigosa',
            new_name='pyeonggawon',
        ),
    ]
